myquizapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quiz_app.urls')),
    path('',include('users.urls', namespace='users')),

]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz_app/urls.py
from django.urls import path
from .views import CourseListView,course_detail_view, course_data_view, save_data_view

app_name = 'quiz'



urlpatterns = [
    path('',CourseListView.as_view(),name='course-list'),
    path('<int:pk>/',course_detail_view,name='course-detail'),
    path('<int:pk>/data/',course_data_view,name='course-data-view'),
    path('<int:pk>/save/',save_data_view,name='save-data-view'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import UserRegisterForm, UserLoginView,UserProfileView, UserPasswordChangeView, UserPasswordResetDoneView,UpdateUserProfileView,CreateUserProfileView #user_profile_view

app_name = 'users'



urlpatterns = [
    path('register/',UserRegisterForm.as_view(), name='register'),
    path('login/',UserLoginView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(next_page='users:login'), name='logout'),
    path('profile/',UserProfileView.as_view(),name='profile'),
    path('profile/create/',CreateUserProfileView.as_view(),name='create-profile'), 
    path('profile/update/<int:pk>/',UpdateUserProfileView.as_view(),name='update-profile'), 
    path('change-password/',UserPasswordChangeView.as_view(),name='password-change'),
    path('change-password/done/',UserPasswordResetDoneView.as_view(),name='password-reset-done')
]

quiz_app/models.py
# import random
from django.db import models

# Create your models here.


class Course(models.Model):
    course_title = models.CharField(max_length=150)
    number_of_questions = models.IntegerField()
    duration = models.IntegerField(help_text='duration of course in minutes',blank=True, null=True)

    def __str__(self):
        return self.course_title

    def get_questions(self):
        '''
        ---do this to get random questions---
        questions = list(self.question_set.all()) 
        random.shuffle(questions)
        return questions[:self.number_of_questions]
        '''
        questions = self.question_set.all()  
        return questions[:self.number_of_questions]

quiz_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import ListView
from .models import Course
from users.models import Result
from quiz_questions.models import Question, Answer
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.



class CourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'quiz_app/index.html'
    context_object_name = 'course_list'



def course_detail_view(request, pk):
    course = Course.objects.get(pk=pk)
    return render(request,'quiz_app/quiz_detail.html',{
        'obj': course
    })


def course_data_view(request, pk):
    course = Course.objects.get(pk=pk)    
    questions = []
    for quest in course.get_questions():
        answers = []
        for ans in quest.get_answers():
            answers.append(ans.answer_text)
        questions.append({quest.question_text: answers })   
    return JsonResponse({
        'data': questions,
        'time': course.duration
    })  

def save_data_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')
        for key in data_.keys():
            question = Question.objects.get(question_text=key)
            questions.append(question)

        user = request.user
        course = Course.objects.get(pk=pk)

        score = 0
        multiplier = 100 / course.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.question_text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for answer in question_answers:
                    if a_selected == answer.answer_text:
                        if answer.correct:
                            score += 1
                            correct_answer = answer.answer_text
                    else:
                        if answer.correct:
                            correct_answer = answer.answer_text       

                results.append({q.question_text: {'correct_answer': correct_answer, 'answered': a_selected} })
            else:
                question_answers = Answer.objects.filter(question=q)
                for answer in question_answers:
                    if not a_selected:
                        correct_answer = answer.answer_text
                results.append({q.question_text: {'correct_answer': correct_answer,'not answered': 'none'} })

        score_ = score * multiplier    
        Result.objects.create(course=course, user=user, score=score_)    

        return JsonResponse({'score': score_, 'results': results})

quiz_app/templates/quiz_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>QuizApp</title>
    {% endblock title %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'quiz_app/style.css' %}">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

</head>
<body>
    <nav class="navbar navbar-light bg-dark px-3">
        <a class="navbar-brand text-muted" href="{% url 'quiz:course-list' %}">
            <span class="home-label">QuizApp</span>
        </a>

        <ul class="nav">
            {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:profile' %}">
                <span class="material-icons"> account_circle </span>
                <!-- <span class="label">Profile</span> -->
            </a>
            
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">
                <span class="material-icons"> logout </span>
                <!-- <span class="label">logout</span> -->
            </a>
          </li>

          {% endif %}
          
        </ul>
    </nav> 


{% if messages %}
    {% for message in messages %}
        <div class="text-center alert alert-{{ message.tags }}">
            welcome {{request.user}} {{ message }} <br>
            click on any of the courses to start quiz
        </div>
    {% endfor %}
{% endif %}

    

    {% block content %}
    {% endblock content %}
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>


    {% block script %} 
    {% endblock script %}

</body>
</html>

quiz_app/templates/quiz_app/index.html
{% extends 'quiz_app/base.html' %}
{% load static %}


{% block title %}
<title>QuizApp</title>
{% endblock title %}



{% block content %}

  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <!-- <h5 class="modal-title" id="staticBackdropLabel">Start  </h5> -->
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modal-body-data">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">No</button>
          <button type="button" id="start-quiz" class="btn btn-success">Yes</button>
        </div>
      </div>
    </div>
  </div>
<!-- endModal -->



<div id="course-container">
    {% for course in course_list %}
    <div class="card text-center">
        <div class="card-body">
            <button
                class="btn btn-primary modal-btn"
                data-pk="{{course.pk}}"
                data-title="{{course.course_title}}"
                data-numquest="{{course.number_of_questions}}"
                data-time="{{course.duration}}"
                data-bs-toggle="modal"
                data-bs-target="#staticBackdrop"
            >
                {{ course.course_title }}
            </button>
        </div>
      </div>
    {% endfor %}
</div>



{% endblock content %}







  {% block script %} 
    <script src="{% static 'quiz_app/index.js' %}" defer></script>
  {% endblock script %}

quiz_app/templates/quiz_app/quiz_detail.html
{% extends 'quiz_app/base.html' %}
{% load static %}

{% block title %}
<title>{{obj}}</title>
{% endblock title %}




{% block content %}

<div class="row">
    <div class="text-center course-name">
        <h4> {{ obj }} </h4>
    </div>
    <!-- <div class="col text-right" id="timer-box"></div> -->
</div>
<p class="back-btn">
<a href="{% url 'quiz:course-list' %}" class="btn btn-danger">go back</a>
</p>

<form id="quiz-form">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <hr />
<button type="submit" class="btn btn-primary submit-btn">submit</button>
</form>

<div id="score-box" class="container"></div>
<div id="result-box"></div>

<style type="text/css" media="all">
.course-name {
  margin-top: 5px;
}
#quiz-box {
    margin:50px 30px;

}
 .quest {
   margin-bottom: 10px;
 }


.back-btn, .submit-btn {
   position: absolute ;
   right: 30px ;
 }

</style>

{% endblock content %}



{% block script %} 
    <script src="{% static 'quiz_app/quiz.js' %}"></script>
{% endblock script %}

quiz_app/templates/quiz_app/register.html
{% extends 'quiz_app/base.html' %}


{% block content %}

<div class="card bg-dark text-white">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p class="btn btn-primary">
        <input type="submit" value="submit">
        </p>
    </form>
    <p class="text-muted">
       Already have an account? <a href="{% url 'quiz:login' %}">login</a>
    </p>
</div>  

<style>
    input[type=submit]{
       background: none;
       border: none;
       color: white;
    }
    
    .helptext, li {
       color: grey;
    }
    
    .card {
        width: 80vw;
        border: 2px solid black;
        border-radius: 10px;
        padding: 20px;
        margin: 100px auto;
    }
    
    
        input[type=text], input[type=email], input[type=password] {
            text-align: center;
            outline: none;
            border: 1px solid green;
            width: 100%;
            transition: border  2s;
        }
    
        input[type=text]:hover, input[type=email]:hover, input[type=password]:hover {
            border: 1px solid red;
        }
    
       
    </style>

{% endblock content %}