myquizapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quiz_app.urls')),
    path('',include('users.urls', namespace='users')),

]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz_app/urls.py
from django.urls import path
from .views import CourseListView,course_detail_view, course_data_view, save_data_view

app_name = 'quiz'



urlpatterns = [
    path('',CourseListView.as_view(),name='course-list'),
    path('<int:pk>/',course_detail_view,name='course-detail'),
    path('<int:pk>/data/',course_data_view,name='course-data-view'),
    path('<int:pk>/save/',save_data_view,name='save-data-view'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import UserRegisterForm, UserLoginView,UserProfileView, UserPasswordChangeView, UserPasswordResetDoneView,UpdateUserProfileView,CreateUserProfileView #user_profile_view

app_name = 'users'



urlpatterns = [
    path('register/',UserRegisterForm.as_view(), name='register'),
    path('login/',UserLoginView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(next_page='users:login'), name='logout'),
    path('profile/',UserProfileView.as_view(),name='profile'),
    path('profile/create/',CreateUserProfileView.as_view(),name='create-profile'), 
    path('profile/update/<int:pk>/',UpdateUserProfileView.as_view(),name='update-profile'), 
    path('change-password/',UserPasswordChangeView.as_view(),name='password-change'),
    path('change-password/done/',UserPasswordResetDoneView.as_view(),name='password-reset-done')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from quiz_app.models import Course

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=100,default="no department")
    level = models.IntegerField(default=100)
    profile_image = models.ImageField(default='default.jpg',upload_to='profile_pictures')

    def __str__(self):
        return self.user.username


class Result(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField(default=0)
    mod_date = models.DateTimeField(auto_now_add=True)
    
    def save(self, *args, **kwargs):
        self.score = round(self.score, 2)
        super(Result, self).save(*args, **kwargs)
        
    def __str__(self):
        return f"{str(self.user)}: {str(self.course)} => {str(self.score)}"

users/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, PasswordChangeView,PasswordResetDoneView
from .models import Result, Profile
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .custom_form import CustomUserCreationForm
from django.contrib.auth import login
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
from django.views.generic import CreateView



# Create your views here.

class UserRegisterForm(SuccessMessageMixin, FormView):
    template_name = 'users/register.html'
    form_class = CustomUserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('quiz:course-list')
    success_message = "your account was created successfully"

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(UserRegisterForm, self).form_valid(form) 


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('quiz:course-list')


class UserProfileView(LoginRequiredMixin, ListView):
    model = Result
    context_object_name = 'results'
    template_name = 'users/profile.html'
    ordering = ['-mod_date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['results'] = Result.objects.filter(user=self.request.user)
        context['profile_model'] = Profile.objects.filter(user=self.request.user)
        return context

class UpdateUserProfileView(UpdateView):
    model = Profile 
    # context_object_name = 'update-profile'
    template_name = 'users/update_profile.html'
    fields = ['department', 'level', 'profile_image']
    success_url = reverse_lazy('users:profile')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(UpdateUserProfileView, self).form_valid(form)

class CreateUserProfileView(CreateView):
    model = Profile 
    template_name = 'users/create_profile.html'
    fields = ['department', 'level', 'profile_image']
    success_url = reverse_lazy('users:profile')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateUserProfileView, self).form_valid(form)

class UserPasswordChangeView(PasswordChangeView):
    template_name = 'users/password_change.html'
    success_url = reverse_lazy('users:password-reset-done')

class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'          

users/templates/users/create_profile.html
{% extends 'quiz_app/base.html' %}
{% load static %}

{% block title %}
<title>Create Profile</title>
{% endblock title %}



{% block content %}

<div class="card bg-dark text-white">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p class="btn btn-primary">
        <input type="submit" value="create">
        </p>
    </form>
</div>  

<style>
    input[type=submit]{
       background: none;
       border: none;
       color: white;
    }
    

    
    .card {
        width: 80vw;
        border: 2px solid black;
        border-radius: 10px;
        padding: 20px;
        margin: 100px auto;
    }
    
    
    input[type=text], input[type=number] {
        text-align: center;
        outline: none;
        border: 1px solid green;
        width: 100%;
        transition: border  2s;
    }
    
</style>

{% endblock content %} 

users/templates/users/login.html
{% extends 'quiz_app/base.html' %}
{% load static %}

{% block title %}
<title>Login</title>
{% endblock title %}


{% block content %}

<div class="login-form ">
    <div class="content bg-dark text-warning">
       <form action="" method="post">
           {% csrf_token %}
            {{ form.as_p }}
           <p class="btn btn-primary">
               <input type="submit" value="login">
           </p>
           <p class="text-muted">
               Don't have an account? <a href="{% url 'users:register' %}">register</a>
           </p>
       </form>
    </div>
   </div>




<style>
    label {
    display: none;
}


 input[type=text], input[type=password] {
    text-align: center;
    border-radius: 15px;
    outline: none;
    border: 1px solid green;
    height: 50px;
    width: 250px;
    transition: width 2s;
}

input[type=text]:hover,input[type=password]:hover {
    width: 300px;
    border: 1px solid red;
}

input[type=submit]{
    background: none;
    border: none;
    color: white;
} 

 input[type=text]{
    margin-top: 150px;

}

.login-form{
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
}

.content {
    border: 2px solid green;
    height: 500px;
    width: 500px;
    text-align: center;
} 
</style>   
{% endblock content %}

{% block script %} 
<script>
    function myFunction() {
       const username = document.getElementById("id_username").placeholder = "username";
 
       const password = document.getElementById("id_password").placeholder = "password";
    }
    myFunction()
 </script>
    {% endblock script %}

users/templates/users/password_change.html
{% extends 'quiz_app/base.html' %}

{% block title %}
    <title>change password</title>
{% endblock title %}


{% block content %}


<div class="card bg-dark text-white">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p class="btn btn-primary">
        <input type="submit" value="change">
        </p>
    </form>
</div>  

<style>
    input[type=submit]{
       background: none;
       border: none;
       color: white;
    }
    
    .helptext, li {
       color: grey;
    }

    ul.errorlist li {
        color: red;
    }
    
    .card {
        width: 80vw;
        border: 2px solid black;
        border-radius: 10px;
        padding: 20px;
        margin: 100px auto;
    }
    
    
    input[type=text], input[type=password] {
        text-align: center;
        outline: none;
        border: 1px solid green;
        width: 100%;
        transition: border  2s;
    }
    
</style>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'quiz_app/base.html' %}

{% block content %}
<a href="{% url 'users:profile' %}" class="btn bg-primary text-white">Go back</a>

<h5>Your Password has been changed</h5>
<br>


<style>
    .btn {
        margin: 20px;
    }
</style>
{% endblock %}

users/templates/users/profile.html
{% extends 'quiz_app/base.html' %}


{% block title %}
<title>Profile</title>
{% endblock title %}

{% block content %}

<a href="{% url 'quiz:course-list' %}" class="btn btn-danger back-btn">go back</a>

  <div class="card" >
    {% if not profile_model %}
    <p>click the button below to create your profile</p>
    <a href="{% url 'users:create-profile' %}" class="btn btn-lk bg-warning text-white">create profile</a>
    {% else %}
    <img src="{{ user.profile.profile_image.url }}" class="card-img-top" alt="...">
      {% for profile in profile_model %}
    <ul class="list-group list-group-flush">
      <li class="list-group-item" >username: {{ profile.user }}</li>
      <li class="list-group-item">level: {{ profile.level }}</li>
      <li class="list-group-item">department: {{ profile.department }}</li>
    </ul>
      {% endfor %}
    <div class="card-body">
      <a href="{% url 'users:update-profile' request.user.id %}" class="btn btn-lk bg-primary text-white">update profile</a>
      <a href="{% url 'users:password-change' %}" class="btn btn-lk bg-danger text-white">change password</a>
    {% endif %}
  </div>
  </div>


<hr>

<div class="result-card" style="width: 18rem;">
  <table>
    <tr class="text-muted">
      <th>Course</th>
      <th>Score</th>
      <th>Date</th>
    </tr>
  {% for result in results %}
    <tr>
      <td>{{ result.course }}</td>
        {% if result.score < 50 %}
          <td class="bg-danger text-white">{{ result.score }}%</td>
          {% else %}  
          <td class="bg-success text-white">{{ result.score }}%</td>
        {% endif %}
      <td>{{ result.mod_date }}</td>
    </tr>
  {% endfor %}
  </table>
</div>



<style>
    .back-btn {
      position: absolute ;
      right: 30px ;
      margin-top: 5px;
      
    } 

    .card {
      width: 25rem;
      border-radius: 10px;
      padding: 20px;
      margin: 50px auto;
    }

    .btn-lk {
      display: block;
      margin-bottom: 5px;
    }

    table {
      width:400px;
      margin-left: 10px;
      margin-bottom: 100px;
    }

    td, th {
      border: 1px solid grey;
      text-align: center;
    }
</style>

{% endblock content %}

users/templates/users/register.html
{% extends 'quiz_app/base.html' %}

{% block title %}
<title>Register</title>
{% endblock title %}

{% block content %}

<div class="card bg-dark text-white">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p class="btn btn-primary">
        <input type="submit" value="submit">
        </p>
    </form>
    <p class="text-muted">
       Already have an account? <a href="{% url 'users:login' %}">login</a>
    </p>
</div>  

<style>
    input[type=submit]{
       background: none;
       border: none;
       color: white;
    }
    
    .helptext, li {
       color: grey;
    }

    ul.errorlist li {
        color: red;
    }
    
    .card {
        width: 80vw;
        border: 2px solid black;
        border-radius: 10px;
        padding: 20px;
        margin: 100px auto;
    }
    
    
        input[type=text], input[type=email], input[type=password] {
            text-align: center;
            outline: none;
            border: 1px solid green;
            width: 100%;
            transition: border  2s;
        }
    
        input[type=text]:hover, input[type=email]:hover, input[type=password]:hover {
            border: 1px solid red;
        }
    
       
    </style>

{% endblock content %}

users/templates/users/update_profile.html
{% extends 'quiz_app/base.html' %}
{% load static %}

{% block title %}
<title>Update Profile</title>
{% endblock title %}



{% block content %}

<div class="card bg-dark text-white">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p class="btn btn-primary">
        <input type="submit" value="change">
        </p>
    </form>
</div>  

<style>
    input[type=submit]{
       background: none;
       border: none;
       color: white;
    }
    

    
    .card {
        width: 80vw;
        border: 2px solid black;
        border-radius: 10px;
        padding: 20px;
        margin: 100px auto;
    }
    
    
    input[type=text], input[type=number] {
        text-align: center;
        outline: none;
        border: 1px solid green;
        width: 100%;
        transition: border  2s;
    }
    
</style>

{% endblock content %} 